Creating UtilBranch
CS2103AUG2016-F11-C1/main pull request #142
Opened 2016-11-04 00:38 UTC by ChaseYaoCong

# New / Updated Files
> * Creation of FilterUtil to be used for clear, find and list controller , in order to refactor the code into linear style.
> * Updating of StringUtil changing method naming
> * Updating of DateUtil extract out parseMethods to be used by controllers
> * Creation of ParseUtil to parse result from tokenizer which to be used by controllers

# New / Updated test cases
> * Update it with new test cases for the methods I have created

2016-11-04 01:43 UTC, louietyj submitted a review, later dismissed

2016-11-04 01:43 UTC, louietyj commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +     * @parser Natty
What the hell is this line, I've never seen such code documentation markup before.

2016-11-04 01:43 UTC, louietyj commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +     *
Please remove this method, it has been extracted into DateParser. And you're claiming credit for my method.

2016-11-04 02:03 UTC, ChaseYaoCong commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +     *
First of all, I have extracted out this method like on Monday/Tuesday. 
Secondly, I didn't put my matric number as it is created by you.
Will remove it as suggested.

2016-11-04 02:16 UTC, ChaseYaoCong commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +     *
removed

2016-11-04 04:41 UTC, louietyj commented
Only open a PR when you want your code to be reviewed and merged, not when you are still actively working on it.

2016-11-04 04:51 UTC, ChaseYaoCong commented
@louietyj Sorry. I am done with it already. Thanks for notifying me

2016-11-05 07:53 UTC, louietyj commented
@irvinlim Code-wise, LGTM. But this seems to be just a bunch of utility methods (with unit tests) that aren't used anywhere, functionality-wise. We will have to scrutinize much harder when a PR comes in that makes use of these utility methods.

@ChaseYaoCong This may be a bit debatable, but you generally should not be separating PRs by modules / files. PRs should be contain logical units of work that solve an issue. Instead, it's better to incrementally create PRs that add util methods together with the functionality that actually uses the util. Otherwise, we have no idea what the util methods are actually used for, and when the PR that comes in, we will have to come back and think about whether these util methods even make sense in the context of what they are used for.

2016-11-05 08:42 UTC, irvinlim requested changes
@louietyj I think ParseUtil should be combined with DateParser. Otherwise its ok.

@ChaseYaoCong Additionally, I'm updating the authorship for some methods, it's better to put authorship for every single method because of how the collate thing works, wait for my commit

2016-11-05 08:42 UTC, irvinlim commented on src/main/java/seedu/todo/commons/util/ParseUtil.java
> +public class ParseUtil {
Can I recommend that this goes inside of controllers/concerns/DateParser.java? Merge master into your branch and move it there.

2016-11-05 08:50 UTC, ChaseTiong commented on src/main/java/seedu/todo/commons/util/ParseUtil.java
> +public class ParseUtil {
@irvinlim okay. 
@louietyj do you want me to combine refactored clear controller with this PR? So I can also fixes #146 at the same time and use the Util methods I created

2016-11-05 22:25 UTC, closed without merging