New Date Viewing for UI
CS2103AUG2016-F11-C1/main pull request #21
Opened 2016-10-12 07:15 UTC by ChaseYaoCong

Change display from "Today" to "Today 12 October"
Include Tomorrow for a day difference
Removal of magic string in todo.ui and todo.ui.components

2016-10-12 07:21 UTC, louietyj commented
Build failing?

2016-10-12 07:24 UTC, ChaseYaoCong commented
Forgot to update it to new test cases. Just updated

2016-10-12 09:03 UTC, irvinlim requested changes

2016-10-12 09:03 UTC, irvinlim commented on src/main/java/seedu/todo/ui/components/TagList.java
> +    private static final String RIGHT_BRACKET = ")";
Do we really need to extract out brackets and spaces as magic strings?

2016-10-12 09:03 UTC, irvinlim commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +        }
Don't think we should be including the day + month in this method, should be extracted to another method.

2016-10-12 09:03 UTC, irvinlim commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +        }
Also, I think you need to use `.getDisplayName` to get a formatted month value, because right now it's in caps. Can get short name of the month also.

2016-10-12 09:03 UTC, irvinlim commented on src/main/java/seedu/todo/ui/components/TagList.java
> +        return TAG_LABEL + SPACE + LEFT_BRACKET + size + RIGHT_BRACKET;
Should be using `String.format` for this, so that brackets don't need to be extracted into this human-unreadable format.

2016-10-12 09:07 UTC, louietyj commented on src/main/java/seedu/todo/ui/components/TagList.java
> +    private static final String RIGHT_BRACKET = ")";
😂

2016-10-12 09:16 UTC, louietyj requested changes

2016-10-12 09:16 UTC, louietyj commented on src/main/java/seedu/todo/ui/InputHandler.java
> +                };
Please revert this "fix", it's more unreadable than the original chunk, and doesn't follow coding standards.

Standard is to _align the new line with the beginning of the parent element_, and regardless, line continuation indentation should be 4 spaces, not 8.

2016-10-12 12:26 UTC, ChaseTiong commented on src/main/java/seedu/todo/ui/InputHandler.java
> +                };
reverted

2016-10-12 12:26 UTC, ChaseYaoCong commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +        }
Have change the formatting

2016-10-12 21:21 UTC, irvinlim requested changes

2016-10-12 21:21 UTC, irvinlim commented on src/test/java/seedu/address/commons/util/DateUtilTest.java
> +                " " + now.plus(6, ChronoUnit.DAYS).getMonth().getDisplayName(TextStyle.FULL, Locale.US).substring(0, 3));
Do fix indentation for this file to use spaces instead of tabs.

2016-10-12 21:21 UTC, irvinlim commented on src/main/java/seedu/todo/ui/components/TagList.java
> +        return TAG_LABEL + SPACE + String.format("(%s)", size);
Was thinking of `String.format("%s (%s)", TAG_LABEL, size);` actually.

2016-10-12 21:21 UTC, irvinlim commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +        else {
Don't want to nitpick, but should be `} else {` on the same line.

2016-10-12 21:21 UTC, irvinlim commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +        else {
Also, use `String.format` in this method instead of having `SPACE` everywhere might be better I think.

2016-10-12 21:21 UTC, irvinlim commented on src/main/java/seedu/todo/commons/util/DateUtil.java
> +    private static final String SPACE  = " ";
Don't really like having to declare a space as a magic string, maybe use `String.format` in those cases.

2016-10-13 04:52 UTC, irvinlim approved these changes

2016-10-13 13:12 UTC, irvinlim commented on src/main/java/seedu/todo/ui/InputHandler.java
> +                };
@louietyj Please approve changes, thanks

2016-10-13 13:58 UTC, merged