List by diff type
CS2103AUG2016-F11-C1/main pull request #61
Opened 2016-10-15 18:49 UTC by ChaseYaoCong

fixed #30 
Now we are able to list by different command , 
Able to support date, complete, uncomplete and differentiate between task and event.

e.g.
`list complete task`
`list uncomplete task`
`list task by today complete`

2016-10-17 18:30 UTC, louietyj commented on src/main/java/seedu/todo/controllers/ListController.java
> +        if (parsedResult.get("status")[0].contains("uncomplete")) {
Lol... this is very basic stuff that I am teaching my CS1010S students not to do...

```
if True:
    return True
else:
    return False
```

2016-10-17 18:36 UTC, irvinlim requested changes

2016-10-17 18:36 UTC, irvinlim commented on src/main/java/seedu/todo/controllers/ListController.java
> +        tokenDefinitions.put("eventType", new String[] { "event", "task"});
We should add support for plurals, i.e. `list tasks` and `list events`.

2016-10-17 18:36 UTC, irvinlim commented on src/main/java/seedu/todo/controllers/ListController.java
> +        if (parsedResult.get("status")[0].contains("uncomplete")) {
^

2016-10-17 18:36 UTC, irvinlim commented on src/main/java/seedu/todo/controllers/ListController.java
> +            isEvent = false;
Maybe you want to use a else if instead of reassigning isTask and isEvent

2016-10-17 18:36 UTC, irvinlim commented on src/main/java/seedu/todo/controllers/ListController.java
> +                System.out.println(LocalDateTime.now());
Please remove println before merging!

2016-10-18 03:23 UTC, ChaseYaoCong commented on src/main/java/seedu/todo/controllers/ListController.java
> +        tokenDefinitions.put("eventType", new String[] { "event", "task"});
updated as suggested. 
Now it support plurals

2016-10-18 03:24 UTC, ChaseYaoCong commented on src/main/java/seedu/todo/controllers/ListController.java
> +            isEvent = false;
update as suggested. Remove unnecessary boolean value.

2016-10-18 03:25 UTC, ChaseYaoCong commented on src/main/java/seedu/todo/controllers/ListController.java
> +                System.out.println(LocalDateTime.now());
removed! opps ><

2016-10-18 14:07 UTC, louietyj requested changes
I created an event and a task.

`list tasks` shows the event without the task.

Did you test your code before creating PR?

2016-10-18 14:09 UTC, ChaseYaoCong commented
sorry forget that i edit to support purals

2016-10-20 15:05 UTC, merged